import Script from "next/script";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";

import "../public/styles/animate.css";
import "../public/styles/tailwindcss.css";
import "../public/styles/globals.css";
export const metadata = {
  title: "TwiteSoft",
  description: "Generated by create next app",

  icons: {
    icon: "../images/blue-icon.png",
  },
};
export default function RootLayout({
  // Layouts must accept a children prop.
  // This will be populated with nested layouts or pages
  children,
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
        <Script src="./js/script.js" />
      </body>
    </html>
  );
}
